# config/services.yaml
services:
  _defaults:
    autowire: true
    autoconfigure: true

  SprintF\Bundle\Admin\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'

  SprintF\Bundle\Admin\Twig\TwigExtension:
    tags: ['twig.extension']

parameters:
